### ISSUE TITLE
Something not good in the source organization

### ISSUE THREAD

**Issue by doonpy** [cvn-intern-2020/YumYum#29]
I see you use the MVC pattern in this project. But the model layer carries too much role (model and controller).
Do you think it OK?

**Comment by lamnguyencse17** [comment]
We are unable to identify the issues without any examples. If you can quote it in here it will be much clearer

**Comment by lamnguyencse17** [comment]
> I see you use the MVC pattern in this project. But the model layer carries too much role (model and controller).
> Do you think it OK?
We are unable to identify the issues without any examples. If you can quote it in here it will be much clearer

**Comment by doonpy** [comment]
> > I see you use the MVC pattern in this project. But the model layer carries too much role (model and controller).
> > Do you think it OK?
> 
> We are unable to identify the issues without any examples. If you can quote it in here it will be much clearer

Sorry for my mistake.
Example in this file [https://github.com/cvn-intern-2020/YumYum/blob/master/src/server/models/groups.js](https://github.com/cvn-intern-2020/YumYum/blob/master/src/server/models/groups.js)

It not only is a model layer but also is a controller (or service).

**Comment by lamnguyencse17** [comment]
Thank you for your clarification. 

I have looked through Tuong Gio Structure here: https://github.com/cvn-intern-2020/queue_overflow/blob/server/signup/server/services/user.js

I believed this should be the good way of doing this. I never thought this as a MVC pattern (split models and routes) because it's my own habit to properly organize a project.

However in my opinion, with the scale of the project this would be a problem without further confusing team member with the concept of MVC and looking around for the codes they want

**Comment by lamnguyencse17** [comment]
> I believed this should be the good way of doing this. I never thought this as a MVC pattern (split models and routes) because it's my own habit to properly organize a project.

I organize a project with the functions. Models are about database. Routes is for routing (usually a model folder in routes used CRUD, an action folder for more advanced works calling a lot of functions and handling). Special case with auth
